@WebDiaryAPI_HostAddress = http://localhost:5280
@entryId = 2

GET {{WebDiaryAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebDiaryAPI_HostAddress}}/api/DiaryEntries
Accept: application/json

###

GET {{WebDiaryAPI_HostAddress}}/api/DiaryEntries/{{entryId}}
Accept: application/json

###

POST {{WebDiaryAPI_HostAddress}}/api/DiaryEntries
Content-Type: application/json
Accept: application/json

{
  "title": "Sample entry title-222",
  "content": "Some content - 222",
  "created": "2026-09-28T12:00:00Z"
}